version: "3.9"

services:
  gpt4free-ts:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gpt4free-ts
    image: gpt4free-ts:latest
    ports:
      - "13000:3000"
    restart: always
    volumes:
      - ./run:/usr/src/app/run
      - ./public:/usr/src/app/public
    cap_add:
      - "SYS_ADMIN"
    environment:
      #      - TZ=Asia/Shanghai
      - http_proxy=${http_proxy}
      - https_proxy=${http_proxy}
